CMAKE_MINIMUM_REQUIRED(VERSION 3.28.3)
SET(DATABASE_MAJOR_VERSION 0)
SET(DATABASE_MINOR_VERSION 1)
SET(DATABASE_VERSION ${DATABASE_MAJOR_VERSION}.${DATABASE_MINOR_VERSION})
PROJECT(database VERSION ${DATABASE_VERSION})
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -ggdb")
SET(CMAKE_CXX_STANDARD 26)
MESSAGE("Build ${PROJECT_NAME} ${CMAKE_PROJECT_VERSION}")
ADD_EXECUTABLE(db main.cpp row.cpp storage_engine.cpp table.cpp column.cpp field.cpp)